### ISSUE TITLE
Package is vulnerable to DoS

### ISSUE THREAD

**Issue by Ilshidur** [marcells/bloggy#8]
Snyk report : https://snyk.io/test/npm/bloggy/0.0.21

The way to fix this issue is to upgrade glob [4.0.5](https://snyk.io/test/npm/glob/4.0.5) to version [7.1.2](https://snyk.io/test/npm/glob/7.1.2).

The other vulnerability can't be fixed at the moment.

If necessary, I can open a PR and upgrade it myself (also making sure it doesn't break anything).

EDIT : Made a [pull request](https://github.com/marcells/bloggy/pull/9).

**Comment by marcells** [comment]
That would be very great. Feel free to make a PR. I will test it, too. And then release a new version to npm.
